services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Derhansen\SfYubikey\:
        resource: '../Classes/*'

    Derhansen\SfYubikey\Command\CheckYubiKeyOtpCommand:
        tags:
            - name: 'console.command'
              command: 'sf_yubikey:checkyubikeyotp'
              schedulable: true

    Derhansen\SfYubikey\Authentication\Mfa\Provider\Yubikey\YubikeyProvider:
        tags:
            - name: mfa.provider
              identifier: 'yubikey'
              title: 'LLL:EXT:sf_yubikey/Resources/Private/Language/locallang.xlf:yubikey.title'
              description: 'LLL:EXT:sf_yubikey/Resources/Private/Language/locallang.xlf:yubikey.description'
              setupInstructions: 'LLL:EXT:sf_yubikey/Resources/Private/Language/locallang.xlf:yubikey.setupInstructions'
              icon: 'ext-sfyubikey-icon'
